[package]
name = "type-id"
version = "0.1.0"
edition = "2021"

[dependencies]
ckb-std = { version = "0.17.0", features = [ "type-id" ] }

[features]
library = []
native-simulator = ["library", "ckb-std/native-simulator"]
