import { EcoCardProps } from "@site/src/components/EcoCard";

const ecoCardContents: EcoCardProps[] = [
    
    {
        title: '.bit',
        description: 'Cross-chain Web3 identities for you and your community',
        href: 'https://did.id/',
        bannerSrc: '.bit',
        tags: ['DID'],
        links: [
        { label: 'website', href: 'https://did.id/' },
        { label: 'github', href: 'https://github.com/dotbitHQ' },
        { label: 'doc', href: 'https://www.notion.so/bit-Previously-DAS-5cea5b425b204679b8ef2855ed94b04d'},
        ],
    },
    {
        title: 'Omiga',
        description: 'The 1st inscription protocol established on Nervos $CKB blockchain',
        href: 'https://omiga.io/',
        bannerSrc: 'omiga',
        tags: ['Protocol', 'DApp'],
        links: [
        { label: 'website', href: 'https://omiga.io/' },
        { label: 'doc', href: 'https://docs.omiga.io/' },
        ],
    },
    {
        title: 'CoTA',
        description: 'A layer-1.5 account based token protocol on Nervos CKB',
        href: 'https://www.cotadev.io/',
        bannerSrc: 'cota',
        tags: ['Protocol', 'NFT'],
        links: [
        { label: 'website', href: 'https://www.cotadev.io/' },
        { label: 'doc', href: 'https://www.cotadev.io/docs/getting-started/overview' },
        ],
    },
    {
        title: 'RGB++',
        description: 'An extended RGB protocol to manage state changes and transaction verification',
        href: 'https://github.com/ckb-cell/RGBPlusPlus-design',
        bannerSrc: 'rgb++',
        tags: ['Protocol'],
        links: [
        { label: 'github', href: 'https://github.com/ckb-cell/RGBPlusPlus-design' },
        { label: 'doc', href: 'https://github.com/ckb-cell/RGBPlusPlus-design/blob/main/docs/light-paper-en.md' },
        ],
    },
    {
        title: 'Spore',
        description: 'Craft, Secure, Distribute, and Monetize DOBs',
        href: 'https://spore.pro/',
        bannerSrc: 'spore',
        tags: ['Protocol', 'DOB'],
        links: [
        { label: 'website', href: 'https://spore.pro/' },
        { label: 'doc', href: 'https://docs.spore.pro/' },
        ],
    },
    {
        title: 'Nervape',
        description: 'A Metaverse with an ongoing Story and NFTs Shaped by the Community',
        href: 'https://nervape.com/',
        bannerSrc: 'nervape',
        tags: ['NFT'],
        links: [
        { label: 'website', href: 'https://nervape.com/' },
        { label: 'github', href: 'https://github.com/nervape' },
        { label: 'doc', href: 'https://tourmaline-elderberry-f93.notion.site/Nervape-Community-Wiki-e46261f411ed42e19b859f48da06fe63' },
        ],
    },
    {
        title: 'JoyGift',
        description: 'Sending crypto assets as gifts to your friends, communities, or users',
        href: 'https://joygift.cc/',
        bannerSrc: 'joygift',
        tags: ['DApp'],
        links: [
        { label: 'website', href: 'https://joygift.cc/' },
        ],
    },
    {
        title: 'Philosopher\'s Stone',
        description: 'On-Chain Gifting Platform powered by the Spore Protocol',
        href: 'https://philosopherstone.xyz/',
        bannerSrc: 'philosopherstone',
        tags: ['DApp', 'DOB'],
        links: [
        { label: 'website', href: 'https://philosopherstone.xyz/' },
        { label: 'github', href: 'https://github.com/SpectreMercury/PhilosopherStone' },
        ],
    },
    {
        title: 'NFTnation',
        description: 'Explore, buy and sell NFTs. By the community, for the community',
        href: 'https://nft-nation.live/',
        bannerSrc: 'nftnation',
        tags: ['NFT'],
        links: [
        { label: 'website', href: 'https://nft-nation.live/' },
        { label: 'doc', href: 'https://nftnation.gitbook.io/nftnation-explained' },
        ],
    },
    {
        title: 'CKB Explorer',
        description: 'A CKB Explorer built with React and Ruby on Rails',
        href: 'https://explorer.nervos.org/',
        bannerSrc: 'explorer',
        tags: ['Explorer'],
        links: [
        { label: 'website', href: 'https://explorer.nervos.org/' },
        { label: 'github', href: 'https://github.com/nervosnetwork/ckb-explorer' },
        ],
    },
    {
        title: 'Nervos Scan',
        description: 'A CKB Explorer produced with love by 7774.bit',
        href: 'https://nervosscan.com/',
        bannerSrc: 'nervosscan',
        tags: ['Explorer'],
        links: [
        { label: 'website', href: 'https://nervosscan.com/' },
        ],
    },
    {
        title: 'Neuron',
        description: 'A versatile desktop wallet designed for securely managing CKB assets',
        href: 'https://github.com/nervosnetwork/neuron/releases/tag/v0.114.2',
        bannerSrc: 'neuron',
        tags: ['Wallet'],
        links: [
        { label: 'website', href: 'https://github.com/nervosnetwork/neuron/releases/tag/v0.114.2' },
        ],
    },
    {
        title: 'JoyID',
        description: 'A web-based passwordless and mnemonic-free wallet solution',
        href: 'https://joy.id/',
        bannerSrc: 'joyid',
        tags: ['Wallet'],
        links: [
        { label: 'website', href: 'https://joy.id/' },
        { label: 'github', href: 'https://github.com/nervina-labs?q=joyid' },
        ],
    },
    {
        title: 'CKBull',
        description: 'A mobile wallet that allows you to access and manage your CKB',
        href: 'https://ckbull.app/',
        bannerSrc: 'ckbull',
        tags: ['Wallet'],
        links: [
        { label: 'website', href: 'https://ckbull.app/' },
        { label: 'doc', href: 'https://www.notion.so/How-to-use-CKBull-wallet-89153cac673447b0bf827d1f6f7d151c?pvs=4'},
        ],
    },
    {
        title: 'imToken',
        description: 'A built-in CKB wallet on mobile that enables users to safely send, receive and store CKB',
        href: 'https://token.im/',
        bannerSrc: 'imtoken',
        tags: ['Wallet'],
        links: [
        { label: 'website', href: 'https://token.im/' },
        { label: 'github', href: 'https://github.com/consenlabs' },
        { label: 'doc', href: 'https://medium.com/imtoken/imtoken-2-5-0-now-with-nervos-tron-bch-ltc-support-14d7171ccf4' },
        ],
    },
    {
        title: 'SafePal',
        description: 'A hardware wallet that supports both Nervos L1 CKB and L2 Godwoken',
        href: 'https://www.safepal.com/',
        bannerSrc: 'safepal',
        tags: ['Wallet'],
        links: [
        { label: 'website', href: 'https://www.safepal.com/' },
        { label: 'doc', href: 'https://www.notion.so/How-to-add-send-Nervos-Chain-CKB-coin-with-SafePal-Hardware-Wallet-40da32d8f7074563859e9d08b585768e'},
        ],
    },
    {
        title: 'Ledger',
        description: 'Provide secure hardware wallets for cryptocurrency storage and management',
        href: 'https://www.ledger.com/',
        bannerSrc: 'ledger',
        tags: ['Wallet'],
        links: [
        { label: 'website', href: 'https://www.ledger.com/' },
        { label: 'doc', href: 'https://developers.ledger.com/docs/sections'},
        ],
    },
    {
        title: 'imKey',
        description: 'Offer secure, user-friendly hardware wallets for digital asset protection',
        href: 'https://imkey.im/',
        bannerSrc: 'imkey',
        tags: ['Wallet'],
        links: [
        { label: 'website', href: 'https://imkey.im/' },
        ],
    },
    {
        title: 'oneKey',
        description: 'Offer secure hardware wallets with cross-platform apps for digital asset management',
        href: 'https://onekey.so/',
        bannerSrc: 'onekey',
        tags: ['Wallet'],
        links: [
        { label: 'website', href: 'https://onekey.so/' },
        { label: 'github', href: 'https://github.com/OneKeyHQ/'},
        { label: 'doc', href: 'https://developer.onekey.so/'},
        ],
    },
    {
        title: 'ForceBridge',
        description: 'A cross-chain interoperability bridge b/w Nervos and other blockchains',
        href: 'https://forcebridge.com/',
        bannerSrc: 'forcebridge',
        tags: ['Bridge'],
        links: [
        { label: 'website', href: 'https://forcebridge.com/' },
        { label: 'github', href: 'https://github.com/nervosnetwork/force-bridge'},
        { label: 'doc', href: 'https://github.com/nervosnetwork/force-bridge/blob/main/docs/dapp-user-guide.md'},
        ],
    },
    {
        title: 'Godwoken Bridge',
        description: 'A token bridge between CKB and Godwoken',
        href: 'https://bridge.godwoken.io/',
        bannerSrc: 'godwokenbridge',
        tags: ['Bridge'],
        links: [
        { label: 'website', href: 'https://bridge.godwoken.io/' },
        { label: 'github', href: 'https://github.com/godwokenrises/light-godwoken/tree/develop/apps/godwoken-bridge'},
        { label: 'doc', href: 'https://docs.godwoken.io/'},
        ],
    },
    {
        title: 'Yokaiswap Bridge',
        description: 'A cross-chain interoperability bridge b/w Nervos and other blockchains',
        href: 'https://www.yokaiswap.com/bridge/',
        bannerSrc: 'yokaiswap',
        tags: ['Bridge'],
        links: [
        { label: 'website', href: 'https://www.yokaiswap.com/bridge/' },
        { label: 'github', href: 'https://github.com/yokaiswap'},
        ],
    },
    {
        title: 'Ankr',
        description: 'The fastest, most reliable Web3 infrastructure',
        href: 'https://www.ankr.com/',
        bannerSrc: 'ankr',
        tags: ['Tools & Infra'],
        links: [
        { label: 'website', href: 'https://www.ankr.com/' },
        { label: 'doc', href: 'https://archive.nervos.org/blog/ankr-integrates-support-for-nervos-nodes' },
        ],
    },
    {
        title: 'Axon',
        description: 'A L2 framework that unleashes the power of appchain future',
        href: 'https://axonweb3.io/',
        bannerSrc: 'axon',
        tags: ['Tools & Infra'],
        links: [
        { label: 'website', href: 'https://axonweb3.io/' },
        { label: 'github', href: 'https://github.com/axonweb3/axon' },
        { label: 'doc', href: 'https://docs.axonweb3.io/' },
        ],
    },
    {
        title: 'BandProtocol',
        description: 'A L2 framework that unleashes the power of appchain future',
        href: 'https://www.bandprotocol.com/',
        bannerSrc: 'bandprotocol',
        tags: ['Tools & Infra'],
        links: [
        { label: 'website', href: 'https://www.bandprotocol.com/' },
        { label: 'github', href: 'https://github.com/bandprotocol' },
        { label: 'doc', href: 'https://medium.com/bandprotocol/band-protocol-integrates-with-nervos-godwoken-361546e1091d' },
        ],
    },
    {
        title: 'DIA',
        description: 'Provides fully customizable and transparent data feeds for smart contracts',
        href: 'https://www.diadata.org/',
        bannerSrc: 'dia',
        tags: ['Tools & Infra'],
        links: [
        { label: 'website', href: 'https://www.diadata.org/' },
        { label: 'doc', href: 'https://archive.nervos.org/blog/dia-deploys-oracles-onto-layer-2-bolstering-dev-resources' },
        ],
    },
    {
        title: 'Godwoken',
        description: 'An EVM-compatible, L2 optimistic rollup solution built on Nervos L1',
        href: 'https://www.godwoken.com/',
        bannerSrc: 'godwoken',
        tags: ['Tools & Infra'],
        links: [
        { label: 'website', href: 'https://www.godwoken.com/' },
        { label: 'github', href: 'https://github.com/godwokenrises' },
        { label: 'doc', href: 'https://docs.godwoken.io/' },
        ],
    },
    {
        title: 'Khalani',
        description: 'A decentralized infrastructure for collaborative solving in intent-driven applications',
        href: 'https://khalani.network/',
        bannerSrc: 'khalani',
        tags: ['Tools & Infra'],
        links: [
        { label: 'website', href: 'https://khalani.network/' },
        { label: 'doc', href: 'https://blog.khalani.network/' },
        ],
    },
    {
        title: 'Perun',
        description: 'A L2 solution enhancing efficiency with off-chain transaction capabilities',
        href: 'https://perun.network/',
        bannerSrc: 'perun',
        tags: ['Tools & Infra'],
        links: [
        { label: 'website', href: 'https://perun.network/' },
        { label: 'github', href: 'https://github.com/perun-network/go-perun' },
        ],
    },
    {
        title: 'Unifra',
        description: 'A leading L2 platform that provides open, reliable infrastructure services',
        href: 'https://unifra.io/',
        bannerSrc: 'unifra',
        tags: ['Tools & Infra'],
        links: [
        { label: 'website', href: 'https://unifra.io/' },
        ],
    },
];

export default ecoCardContents;
