[package]
name = "crypto-service-hash"
version = "0.1.0"
edition = "2021"

[dependencies]
ckb-std = "0.17.0"
ckb-crypto-interface = { path = "../../crate/ckb-crypto-interface" }
ckb-script-ipc-common = "1.0.3"

[features]
library = []
native-simulator = ["library", "ckb-std/native-simulator"]
