# .lychee.toml


exclude = [
  "http://localhost:*",
  "https://127.0.0.1:*",
  "http://0.0.0.0:*",
  "https://github.com/*",
]

max-concurrency = 1

accept = ["200..=299", "403"]

exclude-path = [
  "*.png",
  "*.jpg",
  "*.jpeg",
  "*.gif",
  "*.svg",
]

[github]
