export default {
  tutorial: [
    {
      type: "autogenerated",
      dirName: ".",
    },
    {
      type: "category",
      label: "Resources",
      className: "category-resource",
      items: [
        {
          type: "link",
          label: "Positioning Paper",
          href: "https://github.com/nervosnetwork/rfcs/blob/master/rfcs/0001-positioning/0001-positioning.md",
        },
        {
          type: "link",
          label: "CKB RFCs",
          href: "https://github.com/nervosnetwork/rfcs",
        },
        {
          type: "link",
          label: "CKB Dev Log",
          href: "https://github.com/nervosnetwork/ckb/discussions/categories/dev-log",
        }
      ]
    },
  ],
};
