export default {
  "Getting Started": [
    {
      type: "category",
      label: "Getting Started",
      className: "category-getting-started",
      collapsible: false,
      items: [
        "getting-started/how-ckb-works",
        "getting-started/quick-start",
        "getting-started/installation-guide",
        "getting-started/blockchain-networks",
        "getting-started/ckb-vs-btc",
      ],
    },
    {
      type: "category",
      label: "SDK & Devtools",
      className: "category-tool",
      collapsible: false,
      items: [
        "sdk-and-devtool/rust",
        "sdk-and-devtool/go",
        "sdk-and-devtool/java",
        "sdk-and-devtool/ccc",
        "sdk-and-devtool/lumos",
        "sdk-and-devtool/ckb-cli",
        "sdk-and-devtool/offckb",
        "sdk-and-devtool/playground",
        "sdk-and-devtool/devtool",
      ],
    },
    {
      type: "category",
      label: "DApp Tutorials",
      className: "category-dapp",
      collapsible: false,
      items: [
        "dapp/transfer-ckb",
        "dapp/store-data-on-cell",
        "dapp/create-token",
        "dapp/create-dob",
        "dapp/simple-lock",
      ],
    },
    {
      type: "category",
      label: "Integrate Wallets",
      className: "category-integrate-wallets",
      collapsible: false,
      items: [
        "integrate-wallets/intro-to-wallets",
        "integrate-wallets/ccc-wallet",
      ],
    },
    {
      type: "category",
      label: "Serialization (Molecule)",
      className: "category-molecule",
      collapsible: false,
      items: [
        "serialization/serialization-molecule-in-ckb",
        "serialization/features-molecule",
        "serialization/use-in-ckb-scripts",
        "serialization/tools-molecule",
        "serialization/schema-language",
        "serialization/encoding-specs",
        "serialization/example-role-playing-game",
        "serialization/ccc-molecule",
      ],
    },
    {
      type: "category",
      label: "How-Tos",
      className: "category-howto",
      collapsible: false,
      items: [
        "how-tos/how-to-sign-a-tx",
        "how-tos/how-to-query-tx-state",
        "how-tos/how-to-calculate-tx-hash",
        "how-tos/how-to-calculate-script-hash",
        "how-tos/how-to-calculate-code-hash",
      ],
    },
  ],
  "Scripts (Smart Contracts)": [
    {
      type: "category",
      label: "Scripts (Smart Contracts)",
      className: "category-script",
      collapsible: false,
      items: [
        "script/intro-to-script",
        "script/program-language-for-script",
        "script/syscalls-for-script",
        "script/vm-cycle-limits",
        "script/vm-selection",
        "script/type-id",
        "script/spawn-cross-script-calling",
        "script/ckb-script-ipc",
        "script/debug-script",
        "script/script-upgrade-workflow",
        "script/common-script-error-code",
      ],
    },
    {
      type: "category",
      label: "Script Tutorial",
      className: "category-script-tutorial",
      collapsible: false,
      items: [
        "script/minimal-script",
        "script/sudt-script",
        "script/spawn-script",
        "script/js-script",
      ],
    },
    {
      type: "category",
      label: "Rust",
      className: "category-rust",
      collapsible: false,
      items: [
        "script/rust/rust-quick-start",
        "script/rust/rust-build",
        "script/rust/rust-debug",
        "script/rust/rust-api-introduction",
        "script/rust/rust-api-entry",
        "script/rust/rust-api-syscalls",
        "script/rust/rust-api-error",
        "script/rust/rust-api-logger",
        "script/rust/rust-api-type-id",
        "script/rust/rust-api-spawn",
        "script/rust/rust-test",
      ],
    },
    {
      type: "category",
      label: "Common Scripts",
      className: "category-common-scripts",
      collapsible: false,
      items: [
        "common-scripts/omnilock",
        "common-scripts/xudt",
        "common-scripts/spore-protocol",
        "common-scripts/spore-dob-0",
      ],
    },
    {
      type: "category",
      label: "Script Development Course",
      className: "category-full-script-development-series",
      collapsible: false,
      items: [
        "script-course/intro-to-script-1",
        "script-course/intro-to-script-2",
        "script-course/intro-to-script-3",
        "script-course/intro-to-script-4",
        "script-course/intro-to-script-5",
        "script-course/intro-to-script-6",
        "script-course/intro-to-script-7",
        "script-course/intro-to-script-8",
        "script-course/intro-to-script-9",
        "script-course/intro-to-script-10",
      ],
    },
  ],
  "Tech Explanation": [
    {
      type: "category",
      label: "Tech Explanation",
      className: "category-tech-explanation",
      collapsible: false,
      items: [
        "tech-explanation/fee-estimator",
        "tech-explanation/nervos-blockchain",
        "tech-explanation/cell",
        "tech-explanation/cell-model",
        "tech-explanation/capacity",
        "tech-explanation/script",
        "tech-explanation/code-hash",
        "tech-explanation/hash-type",
        "tech-explanation/script-args",
        "tech-explanation/lock-script",
        "tech-explanation/type-script",
        "tech-explanation/lock-type-diff",
        "tech-explanation/script-group-exe",
        "tech-explanation/witness",
        "tech-explanation/ckbhash",
        "tech-explanation/transaction",
        "tech-explanation/cell-deps",
        "tech-explanation/out-point",
        "tech-explanation/dep-type",
        "tech-explanation/dep-group",
        "tech-explanation/header-dep",
        "tech-explanation/cellinput",
        "tech-explanation/previous-output",
        "tech-explanation/outpoint",
        "tech-explanation/since",
        "tech-explanation/outputs",
        "tech-explanation/outputs-data",
        "tech-explanation/block",
        "tech-explanation/header",
        "tech-explanation/rawheader",
        "tech-explanation/transactions",
        "tech-explanation/uncles",
        "tech-explanation/proposals",
        "tech-explanation/ckb-address",
        "tech-explanation/ckb-vm",
        "tech-explanation/consensus",
        "tech-explanation/economics",
        "tech-explanation/glossary",
      ],
    },
  ],
  Ecosystem: [
    {
      type: "category",
      label: "Ecosystem",
      className: "category-ecosystem",
      collapsible: false,
      items: ["ecosystem/projects", "ecosystem/organizations"],
    },
    {
      type: "category",
      label: "History & Hard Forks",
      className: "category-history",
      collapsible: false,
      items: [
        "history-and-hard-forks/intro-to-hard-fork",
        "history-and-hard-forks/ckb-hard-fork-history",
        "history-and-hard-forks/history-vm-version",
        "history-and-hard-forks/rethinking-forks",
      ],
    },
    {
      type: "category",
      label: "Resources",
      className: "category-resources",
      collapsible: false,
      items: [
        {
          type: "link",
          label: "Positioning Paper",
          href: "https://github.com/nervosnetwork/rfcs/blob/master/rfcs/0001-positioning/0001-positioning.md",
        },
        {
          type: "link",
          label: "CKB RFCs",
          href: "https://github.com/nervosnetwork/rfcs",
        },
        {
          type: "link",
          label: "CKB Dev Log",
          href: "https://github.com/nervosnetwork/ckb/discussions/categories/dev-log",
        },
        {
          type: "link",
          label: "CKB Academy",
          href: "https://academy.ckb.dev/",
        },
        {
          type: "link",
          label: "CKB Cookbook",
          href: "https://cookbook.ckbdapps.com/",
        },
      ],
    },
    {
      type: "category",
      label: "Other Protocols",
      className: "category-other-protocols",
      collapsible: false,
      items: [
        {
          type: "link",
          label: "Fiber network",
          href: "https://www.fiber.world/docs",
        },
        {
          type: "link",
          label: "Spore Protocol",
          href: "https://docs.spore.pro",
        },
      ],
    },
  ],
  "Nodes & Mining": [
    {
      type: "category",
      label: "Network & Nodes",
      className: "category-node",
      collapsible: false,
      items: [
        "node/rpcs",
        "node/run-mainnet-node",
        "node/run-testnet-node",
        "node/run-devnet-node",
        "node/run-light-client-node",
        "node/run-public-rpc-node",
        "node/turn-on-fee-estimator",
      ],
    },
    {
      type: "category",
      label: "Mining",
      className: "category-mining",
      collapsible: false,
      items: [
        "mining/algorithm-difficulty",
        "mining/rewards",
        "mining/halving",
        "mining/cost-and-profit",
        "mining/risks",
        "mining/hardware",
        "mining/guide",
        "mining/info-stats",
      ],
    },
  ],
};
