export default {
  tutorial: [
    {
      type: "autogenerated",
      dirName: ".",
    },

    /* Apply customized styling to the coming soon contents. IDs are randomly assigned */
    {
      type: "doc",
      id: "concepts/cell-model",
      label: "Scripts (coming soon...)",
      className: "disabled-menu-link",
    },
    {
      type: "doc",
      id: "concepts/cell-model",
      label: "Run Node (coming soon...)",
      className: "disabled-menu-link",
    },
    {
      type: "doc",
      id: "concepts/cell-model",
      label: "Mining (coming soon...)",
      className: "disabled-menu-link",
    },
  ],
};
