[package]
name = "tx-hash"
version = "0.1.0"
edition = "2021"

[dependencies]
ckb-std = "0.17.0"
blake2b-ref = "0.3.1"

[features]
library = []
native-simulator = ["library", "ckb-std/native-simulator"]
